version: '3'
services:
  web-application:
    build: "./web-application"
    ports:
      - "8000:8080"
      - "9229:9229"
    volumes:
      - "./web-application/src:/web-application/src"
    depends_on:
      - database
      - redis-server
  database:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=theRootPassword
      - MYSQL_DATABASE=webAppDatabase
  redis-server:
    image: redis:7.0.0
    ports:
      - 6379:6379
    expose:
      - 6379
  spa:
    build: ./spa
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - "./spa/src:/usr/share/nginx/src"